# this is prep_cnc.Rmd
create new caledonia repo. 

## 1. setup

```{r setup, eval=F}
dir_spatial = file.path(dir_M, 'git-annex/clip-n-ship', key, 'spatial') 
dir_layers  = file.path(dir_M, 'git-annex/clip-n-ship', key, 'layers') 
dir_custom  = file.path(dir_spatial, 'custom') 
dir_in      = file.path(dir_custom, 'Shape') 
```

## Read shapefile, update name, resave

```{r explore shapefiles, eval=F}
## inspect
shp <-  rgdal::readOGR(dsn = path.expand(dir_in), layer = 'espace_maritime_NC')
shp@data
shp
  
plot(shp)

shp@data <- shp@data %>%
  dplyr::mutate(rgn_id = 1,
                rgn_name = 'Nouvelle-Calédonie') %>%
  dplyr::select(rgn_id, 
                rgn_name, 
                area_km2 = `Surf_km.`)

writeOGR(shp, dsn = dir_spatial, layer = 'cnc_eez', driver = 'ESRI Shapefile', overwrite=TRUE) 

## save rgn_offshore_data.csv on git-annex
readr::write_csv(shp@data %>% 
                   select(rgn_id, rgn_name, area_km2) %>%
                   arrange(rgn_id), 
                 file.path(dir_spatial, 'rgn_offshore_data.csv'))

# save lookup table with unique rgn_ids on github
readr::write_csv(shp@data, sprintf('~/github/ohi-webapps/custom/%s/rgns_custom.csv', key))
```