# This is prep_cdz.Rmd


## 0. add cdz to `sc_studies_custom.csv` 

Add by hand to `ohi-webapps/custom/sc_studies_custom.csv`

## 1. setup
```{r setup, eval=F}

# libraries
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(rgdal)
library(raster)

key = 'cdz'

# directories
dir_neptune = c('Windows' = '//neptune.nceas.ucsb.edu/data_edit',
                'Darwin'  = '/Volumes/data_edit',
                'Linux'   = '/var/data/ohi')[[ Sys.info()[['sysname']] ]]
dir_custom_cdz = '~/github/ohi-webapps/custom/cdz'
dir_annex_sc   = file.path(dir_neptune, 'git-annex/clip-n-ship', key)

# setwd
setwd('~/github/ohi-webapps')

```

## 2. maps
```{r setup, eval=F}

## read in shp files and save with desired headers in data frame.
cdz = readOGR(dsn = file.path(dir_annex, 'cdz/spatial/custom/raw'),
              layer = 'eez_GoC')

## view dataframe and map
cdz@data = cdz@data %>%
  mutate(rgn_id   = 1,
         rgn_name = 'gulfo', 
         area_km2 = area_m2 * 1e-6)

plot(cdz)

## save as shapefiles. will create 4 files: .dbf, .prj, .shp, .shx
writeOGR(cdz, dsn = file.path(dir_annex, 'cdz/spatial/custom'), 
         layer = 'cdz_shp', driver = 'ESRI Shapefile', overwrite=T) 

## create lookup table with unique rgn_ids
cdz_rgns = cdz@data %>%
  select(rgn_id, rgn_name, area_km2)

write_csv(cdz_rgns, '~/github/ohi-webapps/custom/cdz/cdz_rgns_custom.csv')
write_csv(cdz_rgns, file.path(dir_annex_sc, 'spatial/rgn_offshore_data.csv'))


## copy mar_coastalpopn_inland25km.csv from ESP

dir.create(dir_annex_sc, 'layers')
file.copy(file.path(dir_neptune, 'git-annex/clip-n-ship/esp/layers/mar_coastalpopn_inland25km_lyr.csv'),
          file.path(dir_neptune, 'git-annex/clip-n-ship/cdz/layers/mar_coastalpopn_inland25km_lyr.csv'))

# need to delete all rgns but rgn 2, Andalucia, and change it to 1. Done by hand, could do it here:
# readLines(file.path(dir_annex_sc, 'layers/mar_coastalpopn_inland25km_lyr.csv')) %>%
#   str_extract_all(


          
          


```

