---
title: "arctic shapefile"
author: "Jamie Afflerbach"
date: "10/24/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries

library(readr)
library(stringr)
library(rgdal)
library(raster)
library(tools)
library(rgeos)
library(maptools)
library(dplyr)

# directories and source files
dir_M     <- c('Windows' = '//mazu.nceas.ucsb.edu/ohi',
               'Darwin'  = '/Volumes/ohi',
               'Linux'   = '/home/shares/ohi')[[ Sys.info()[['sysname']] ]]

#arctic extent
#projection
laeaCRS <- CRS("+init=epsg:3572")

```

Read in each country
```{r ctry}

alaska = readOGR(dsn='spatial/alaska',layer='US_arc')%>%spTransform(laeaCRS)
canada = readOGR(dsn='spatial/canada',layer='canada_and_beaufort')%>%spTransform(laeaCRS)
greenland = readOGR(dsn='spatial/greenland',layer='greenland_eez_east_west')%>%spTransform(laeaCRS)
janmayen = readOGR(dsn='spatial/janmayen',layer='Jan Mayen')%>%spTransform(laeaCRS)
russia   = readOGR(dsn='spatial/russia',layer='russia_in_arctic')%>%spTransform(laeaCRS)
svalbard = readOGR(dsn='spatial/svalbard',layer='svalbard')%>%spTransform(laeaCRS)
norway   = readOGR(dsn='spatial/norway',layer='norway_no_svalbard_crop')%>%spTransform(laeaCRS)

```

Get dataframes in the same format

```{r df}

alaska@data = alaska@data%>%
              mutate(country = 'United States')

canada@data <- canada@data%>%
                mutate(rgn_name = c('Nunavut','Beaufort Sea'))%>%
                dplyr::select(rgn_name, country=Country)

greenland@data <- greenland@data%>%
                mutate(rgn_name = c('west','east'))%>%
                dplyr::select(rgn_name, country=Country)
                    
janmayen@data = janmayen@data%>%
                  mutate(country = 'Norway')%>%
                dplyr::select(rgn_name=rgn_nam, country)

russia@data = russia@data%>%
              mutate(rgn_name = 'Russia')%>%
              dplyr::select(rgn_name,country = Country)
          
svalbard@data = svalbard@data%>%
                  mutate(rgn_name = 'svalbard',
                         Country = 'Norway')%>%
                  dplyr::select(rgn_name,country = Country)

norway@data = norway@data%>%
                  mutate(rgn_name = 'norway')%>%
                  dplyr::select(rgn_name,country)


```


Combine them all together

```{r combine}

library(devtools)
#install_git("git://github.com/gsk3/taRifx.geo.git")
library(taRifx.geo)

all = rbind.SpatialPolygonsDataFrame(alaska, canada, russia, svalbard, norway, janmayen, greenland)

areas <- gArea(all, byid=TRUE)  

all@data <- all@data%>%
              mutate(rgn_id = 1:9,
                     area_km2 = areas*1e-6)


#save to github and git-annex (this is prob redundant)
writeOGR(all,dsn='spatial',layer='arctic_eezs',driver="ESRI Shapefile", overwrite=T)
writeOGR(all,dsn=file.path(dir_M, 'git-annex/clip-n-ship/arc/spatial'),layer='arctic_eezs',driver="ESRI Shapefile", overwrite=T)

plot(all)

```



