# this is prep_arc.Rmd

Final arctic_eezs prepared by @jafflerbach in arc_regions.rmd @master branch!

Arctic Regions: 
- Russia rgn_id: 73
- Greenland rgn_id: 145
- USA rgn_id: 163
- Norway rgn_id: 223
- Canada rgn_id: 218

## 1. setup
Just need to rename a few regions
```{r setup, eval=F}
setwd('~/github/ohi-webapps')
devtools::load_all('~/github/ohirepos') #source('~/github/ohi-webapps/_source_and_load.r')
source('create_init.R')            # load all libraries, set directories relevant to all keys
source('create_functions.R')       # all functions for creating and updating repos and webapps

key <- 'arc'

dir_spatial    = file.path(dir_M, 'git-annex/clip-n-ship', key, 'spatial') 
dir_layers     = file.path(dir_M, 'git-annex/clip-n-ship', key, 'layers') 
dir_custom     = file.path(dir_spatial, 'custom') 
```

## Read shapefile, update name, resave

```{r explore shapefiles, eval=F}
## inspect
shp = readOGR(dsn = dir_custom, layer = 'arctic_eezs')
shp@data
str(shp@data)
# plot(shp)
  
## rename a few rgn_names
shp@data$rgn_name = as.character(shp@data$rgn_name)
shp@data$rgn_name[shp@data$rgn_name == 'norway']   = 'Norway'
shp@data$rgn_name[shp@data$rgn_name == 'svalbard'] = 'Svalbard'
shp@data$rgn_name[shp@data$rgn_name == 'west']     = 'West Greenland'
shp@data$rgn_name[shp@data$rgn_name == 'east']     = 'East Greenland'
shp@data$country <- as.character(shp@data$country)
shp@data$country[shp@data$country   == 'NA']       = 'High Seas'

shp@data <- shp@data %>%
  select(rgn_id, rgn_name, country, area_km2)

writeOGR(shp, dsn = dir_spatial, layer = 'arctic_eezs', driver = 'ESRI Shapefile', overwrite=TRUE) 
```

## Create required .csv files
```{r csv files, eval=F}
## rgn_offshore_data.csv
data_arc <- shp@data %>%
  select(-country)
write.csv(data_arc, file.path(dir_spatial, 'rgn_offshore_data.csv'), row.names = FALSE)

## dummy mar_coastalpopn_inland25km_lyr.csv
dir.create(dir_layers)

data_frame(rgn_id = rep(1:max(data_arc$rgn_id), 5), year = rep(2005:2013, 5)) %>%
  mutate(popsum = 100) %>%
  arrange(rgn_id) %>%
  write.csv(file.path(dir_layers, 'mar_coastalpopn_inland25km_lyr.csv'), row.names = FALSE)
```
