# This is prep_mhi.Rmd

## 0. add col to `sc_studies_custom.csv` 

Add by hand to `ohirepos-log/repo_registry.csv`

## 1. setup
```{r setup, eval=F}

# run create_repos.rmd setup chunk

```

## 2. maps
```{r setup, eval=F}

# read in shp files and save with desired headers in data frame.
shp = rgdal::readOGR(dsn = repo_registry$dir_shp_in, layer = repo_registry$name_shp_files)

# view dataframe and map
shp@data
plot(shp)

## clean up
shp@data <- shp@data %>%
  dplyr::select(rgn_id = Id, rgn_name = Zone, area_km2 = Shape_Area)
shp@data$rgn_id[shp@data$rgn_name == "South"] = 1
shp@data$rgn_id[shp@data$rgn_name == "North"] = 2

# save as shapefiles. will create 4 files: .dbf, .prj, .shp, .shx
# writeOGR(shp, dsn = dir_shp, layer = key, driver = 'ESRI Shapefile', overwrite=T) 
# 
# ## ave/rgn_offshore_data.csv on git-annex
# write.csv(shp@data, file.path(dir_shp, 'rgn_offshore_data.csv'))
# 
# # create lookup table with unique rgn_ids
# write_csv(shp@data, sprintf('%s/%s_rgns_custom.csv', dir_custom, key))

```


## 3. prep shp map with custom_maps()
Proceed as in `create_all.r` and run `custom_maps()`

```{r prep col map custom_maps, eval=FALSE}

keys_redo = 'col'
key = keys_redo[1]

setwd(dir_repos)
source(sprintf('%s/ohi-webapps/create_init_sc.R', dir_github))
setwd(dir_repo)

# fun custom_maps
custom_maps(key) 

```

