# This is prep_can-atl.Rmd

## 0. add col to `sc_studies_custom.csv` 

Register to `ohi-webapps/custom/sc_studies_custom.csv`

## 1. setup

```{r setup, eval=F}

## libraries
library(dplyr)
library(rgdal)

## key info
key     <- 'can-atl'
shp_in  <- 'regions_final'

## dirs 
dir_shp <-  sprintf('%s/%s/spatial',dir_annex, key) # for shapefiles
dir_webapps_custom = sprintf('~/github/ohi-webapps/custom/%s', key) # for local shp@data

# setwd
setwd('~/github/ohi-webapps')

```

## 2. maps
```{r setup, eval=F}

## read in shp files and save with desired headers in data frame.
shp = rgdal::readOGR(dsn = dir_shp, layer = shp_in)

# view dataframe and map
shp@data

# shp@data
# ID   REGION  AREA_KM2   AREA_HA X_CENTROID Y_CENTROID          Label                Name                             French_Nam
# 0  12 Atlantic  102524.0  10252373    2308165    3152888   Gulf - Outer        Gulf - Outer                        Golfe - Externe
# 1 12E Atlantic  132558.0  13255771    2308165    3152888   Gulf - Inner        Gulf - Inner                        Golfe - Interne
# 2 12D Atlantic   10468.0   1046814    2308165    3152888 Gulf - Estuary      Gulf - Estuary                       Golfe - Estuaire
# 3   8 Atlantic 1045484.0 104548403    2647640    3679289             10 NL-Labrador Shelves Plateaux de Terre-Neuve et du Labrador
# 4   9 Atlantic  431126.3  43112633    2553012    2614163             11       Scotian Shelf                   Plateau néo-écossais
#                                                              Legend
# 0                                                 12 - Gulf / Golfe
# 1                                                 12 - Gulf / Golfe
# 2                                                 12 - Gulf / Golfe
# 3 10 - NL-Labrador Shelves / Plateaux de Terre-Neuve et du Labrador
# 4                         11 - Scotian Shelf / Plateau néo-écossais

## Plot
# plot(shp) takes a long time!


## clean up
shp@data <- shp@data %>%
  dplyr::mutate(rgn_id = 1:5) %>%
  dplyr::select(rgn_id, 
                rgn_name = Name, 
                area_km2 = AREA_KM2)

# save as shapefiles. will create 4 files: .dbf, .prj, .shp, .shx
writeOGR(shp, dsn = dir_shp, layer = key, driver = 'ESRI Shapefile', overwrite=T)

## save/rgn_offshore_data.csv on git-annex
write.csv(shp@data, file.path(dir_shp, 'rgn_offshore_data.csv'))

# create lookup table with unique rgn_ids
write_csv(shp@data, sprintf('%s/%s_rgns_custom.csv', dir_webapps_custom, key))

```

